# Generated by Django 4.2.16 on 2025-03-10 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
