# Generated by Django 4.2.16 on 2024-12-31 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='file',
            name='temporary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='file',
            name='upload_session',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='file',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.post'),
        ),
    ]
