# Generated by Django 4.2.16 on 2025-03-29 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_post_accepted_solution_post_solved'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='forum.comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.JSONField(),
        ),
    ]
