# Generated by Django 4.2.16 on 2024-12-31 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_rename_uploaded_at_file_created_at_file_temporary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='posts', to='forum.file'),
        ),
    ]
