# Generated by Django 4.2.16 on 2025-04-10 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_remove_comment_upvotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='background_slider',
            field=models.IntegerField(default=50),
        ),
    ]
