# Generated by Django 4.2.16 on 2025-04-10 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0013_userprofile_background_slider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='background_slider',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='background_hue',
            field=models.IntegerField(default=180),
        ),
    ]
