# Generated by Django 4.2.16 on 2025-04-16 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0014_remove_userprofile_background_slider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='block_1A',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='block_1A', to='forum.course'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='block_1B',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='block_1B', to='forum.course'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='block_1D',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='block_1D', to='forum.course'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='block_1E',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='block_1E', to='forum.course'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='block_2A',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='block_2A', to='forum.course'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='block_2B',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='block_2B', to='forum.course'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='block_2C',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='block_2C', to='forum.course'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='block_2D',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='block_2D', to='forum.course'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='block_2E',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='block_2E', to='forum.course'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='background_hue',
            field=models.IntegerField(default=231),
        ),
    ]
