# Generated by Django 4.2.16 on 2025-01-09 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0015_savedpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
    ]
