# Generated by Django 4.2.16 on 2025-04-19 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0015_userprofile_block_1a_userprofile_block_1b_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('block_1', models.CharField(blank=True, max_length=10, null=True)),
                ('block_2', models.CharField(blank=True, max_length=10, null=True)),
                ('block_3', models.CharField(blank=True, max_length=10, null=True)),
                ('block_4', models.CharField(blank=True, max_length=10, null=True)),
                ('block_5', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
