# Generated by Django 4.2.16 on 2025-04-19 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0016_dailyschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyschedule',
            name='block_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dailyschedule',
            name='block_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dailyschedule',
            name='block_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dailyschedule',
            name='block_4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dailyschedule',
            name='block_5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
