# Generated by Django 4.2.16 on 2025-04-22 18:32

import django.contrib.postgres.search
from django.db import migrations
from django.contrib.postgres.search import SearchVector

def update_user_search_vector(apps, schema_editor):
    User = apps.get_model('forum', 'User')
    for user in User.objects.all():
        user.search_vector = (
            SearchVector('first_name', weight='A') +
            SearchVector('last_name', weight='A')
        )
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0019_dailyschedule_ceremonial_uniform'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.RunPython(update_user_search_vector),
    ]
