# Generated by Django 4.2.16 on 2025-03-04 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0019_course_usercoursehelp_usercourseexperience'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(default='Misc', max_length=100),
        ),
    ]
