# Generated by Django 4.2.16 on 2025-03-06 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0020_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='posts', to='forum.course'),
        ),
    ]
