# Generated by Django 4.2.16 on 2025-04-26 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0021_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/default.png', null=True, upload_to='profile_pictures/'),
        ),
    ]
