# Generated by Django 4.2.16 on 2025-05-21 23:26

from django.db import migrations, models
import json
import ast


def convert_text_to_json(apps, schema_editor):
    Solution = apps.get_model('forum', 'Solution')
    for solution in Solution.objects.all():
        try:

            print("A")
            # Step 1: Parse as Python literal (since it uses single quotes)
            python_obj = ast.literal_eval(solution.content)

            print(python_obj)

            # Step 2: Convert to JSON-compliant structure
            solution.content = json.dumps(python_obj)  # Django's JSONField will handle serialization

            solution.save(update_fields=['content'])

        except Exception as e:
            print(f"Skipping Solution ID {solution.id} due to parse error: {e}")
            continue


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0023_dailyschedule_is_school'),
    ]

    operations = [
        migrations.RunPython(convert_text_to_json, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='solution',
            name='content',
            field=models.JSONField(),
        ),
    ]
