# Generated by Django 4.2.16 on 2025-05-12 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0023_dailyschedule_is_school'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at']},
        ),
    ]
