# Generated by Django 4.2.16 on 2025-05-21 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_notification_comment_and_more'),
        ('forum', '0025_post_views'),
    ]

    operations = [
    ]
