# Generated by Django 4.2.16 on 2025-05-22 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0024_auto_20250521_2326'),
        ('forum', '0026_merge_20250521_2049'),
    ]

    operations = [
    ]
