# Generated by Django 4.2.16 on 2025-07-09 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0028_postlike_remove_post_tags_delete_tag_postlike_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
