# Generated by Django 4.2.16 on 2025-07-10 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0029_post_is_anonymous'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='code',
        ),
    ]
