# Generated by Django 4.2.16 on 2025-07-10 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0030_remove_course_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='forum.course')),
            ],
        ),
    ]
