# Generated by Django 4.2.16 on 2025-07-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0031_coursealias'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='wolfnet_password',
            field=models.CharField(blank=True, help_text='Your WolfNet password for grade notifications and schedule integration', max_length=255, null=True),
        ),
    ]
