# Generated by Django 4.2.16 on 2025-07-15 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0032_userprofile_wolfnet_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradebookSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_id', models.CharField(max_length=32)),
                ('marking_period_id', models.CharField(max_length=32)),
                ('json_data', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradebook_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'section_id', 'marking_period_id', 'timestamp')},
            },
        ),
    ]
