# Generated by Django 4.2.16 on 2025-08-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0033_gradebooksnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='expo_push_token',
            field=models.CharField(blank=True, help_text='Expo push notification token for mobile app notifications', max_length=255, null=True),
        ),
    ]
