# Generated by Django 4.2.16 on 2025-08-09 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0034_userprofile_expo_push_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('post', 'New Post'), ('solution', 'New Solution'), ('comment', 'New Comment'), ('reply', 'New Reply'), ('grade_update', 'Grade Update'), ('edit', 'Post Edit')], max_length=20),
        ),
    ]
