# Generated by Django 4.2.16 on 2025-08-15 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0035_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyschedule',
            name='block_6',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dailyschedule',
            name='block_6_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dailyschedule',
            name='block_7',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dailyschedule',
            name='block_7_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dailyschedule',
            name='block_8',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dailyschedule',
            name='block_8_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
