# Generated by Django 4.2.16 on 2025-08-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0036_dailyschedule_block_6_dailyschedule_block_6_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True)),
                ('label', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='blocks',
            field=models.ManyToManyField(blank=True, related_name='courses', to='forum.block'),
        ),
    ]
