# Generated by Django 4.2.16 on 2025-08-20 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0037_block_course_blocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='max_grade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='grade_level',
            field=models.IntegerField(blank=True, help_text="User's current grade level (e.g., 11)", null=True),
        ),
    ]
